VOICE_BY_LANG_AND_SEX = {
    "🇮🇹 Italian (Male)": "it-IT-DiegoNeural",
    "🇮🇹 Italian (Female)": "it-IT-ElsaNeural",
    "🇷🇺 Russian (Male)": "ru-RU-DmitryNeural",
    "🇷🇺 Russian (Female)": "ru-RU-SvetlanaNeural",
    "🇫🇷 French (Male)": "fr-CH-FabriceNeural",
    "🇫🇷 French (Female)": "fr-CH-ArianeNeural",
    "🇬🇧 English (Male)": "en-GB-RyanNeural",
    "🇬🇧 English (Female)": "en-GB-SoniaNeural",
    "🇵🇹 Portuguese (Male)": "pt-PT-DuarteNeural",
    "🇵🇹 Portuguese (Female)": "pt-PT-RaquelNeural",
    "🇪🇸 Spanish (Male)": "es-ES-AlvaroNeural",
    "🇪🇸 Spanish (Female)": "es-ES-ElviraNeural",
    "🇩🇪 German (Male)": "de-DE-ConradNeural",
    "🇩🇪 German (Female)": "de-DE-KatjaNeural",
    "🇵🇱 Polish (Male)": "pl-PL-MarekNeural",
    "🇵🇱 Polish (Female)": "pl-PL-ZofiaNeural",
    "🇸🇦 Arabic (Male)": "ar-SA-HamedNeural",
    "🇸🇦 Arabic (Female)": "ar-SA-ZariyahNeural",
    "🇯🇵 Japanese (Male)": "ja-JP-KeitaNeural",
    "🇯🇵 Japanese (Female)": "ja-JP-NanamiNeural",
    "🇨🇳 Chinese Mandarin (Male)": "zh-CN-YunzeNeural",
    "🇨🇳 Chinese Mandarin (Female)": "zh-CN-XiaoxiaoNeural",
    "🇰🇷 Korean (Male)": "ko-KR-InJoonNeural",
    "🇰🇷 Korean (Female)": "ko-KR-SunHiNeural",
    "🇹🇷 Turkish (Male Only)": "tr-TR-AhmetNeural",
    "🇳🇱 Dutch (Male)": "nl-NL-CoenNeural",
    "🇳🇱 Dutch (Female)": "nl-NL-FennaNeural",
}
